### ISSUE TITLE
Bundle FUXA for static demo site

### ISSUE THREAD

**Issue by concept10** [frangoteam/frangoteam.github.io#1]
@unocelli - Would you mind sharing how you bundled FUXA to be used for static site server, such as GitHub.io?  I think this is very interesting.  Thanks in advance.

**Comment by unocelli** [comment]
I build the FUXA frontend with configuration 'demo':
```
$ cd client
$ ng build --configuration=demo
```
then in ./client/dist you have the static site to serve

**Comment by concept10** [comment]
Thanks for the insight.  Closing the issue.  ;)
